### ISSUE TITLE
Base layer - add in/overlay option. Show Region/District boundaries

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/ByBecApp#15]
Harry Kope was intereted in being able to see the Region/District boundaries on the map.
Also there is an outstanding issue with scaling of the text on the base maps particularly with the town names being too small to be read

**Comment by kdaust** [comment]
@whmacken I've added district outlines, but not regions, because I would need to upload another layer. Not a big deal, just wanted to check it was necessary first. Also wanted to ask about district interactivity - do we want to be able to select a specific district?
