### ISSUE TITLE
Transparency Issue

### ISSUE THREAD

**Issue by kdaust** [FLNRO-Smithers-Research/ByBecApp#16]
- [x] When one navigates to the Find a BGC Tab, all other tabs increase the BGC opacity. They shouldn't be linked.
- [x] The icon image link for the slider is broken 
- [x] Label on the slider if possible so that people see it and know what it will do
- [ ] Refresh the transparency with slider changes rather than requiring a map move if this is possible ** Not priority

**Comment by whmacken** [comment]
BGC transparency slider does not work at all currently
