### ISSUE TITLE
Update Map tiling in App

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/ByBecApp#21]
Still uses old BGCv12 map with error in it.
All apps should use a common map tile base so that only one update is required if this is possible

**Comment by kdaust** [comment]
Roger - they all use the same tiles, except that I need a different version for WNA vs just BC; I haven't updated the WNA one yet.

**Comment by whmacken** [comment]
Still need to update the WNA tiles - the current one still shows the incorrect MSdc3 polygon
