### ISSUE TITLE
Feasibility

### ISSUE THREAD

**Issue by whmacken** [FLNRO-Smithers-Research/ByBecApp#3]
Fix spacing, make radio buttons inline, make edatopic grid smaller
Put find a BGC in its own tab
Add hillshade baselayer
Try and make map height dynamic, add rule under map
Make sure squares work

**Comment by kdaust** [comment]
Still not sure what's up with the squares...works great locally and then doesn't as soon as it's on the server. Might try going back to the standard leaflet marker
